version: '3'

services:
  evmosnodelocal:
    image: evmosnodelocal
    container_name: evmosnodelocal0
    build:
      context: ../
      dockerfile: docker/Dockerfile.evmos-node.local
    ports:
      - "26656-26657:26656-26657"
      - "8545:8545"
    volumes:
      - ../running_node/node1:/root:Z
      - ../private.ed25519:/config/private.ed25519:Z
      - ../public.ed25519:/config/public.ed25519:Z
      - ../node/init_scripts/setup.sh:/config/setup.sh:Z
      - ../node/zama_config/zama_config_local_testnet.toml:/config/zama_config.toml:Z
      - ../vm.log:/root/.evmosd/zama/vm.log:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  oracledb:
    container_name: zbcoracledb
    build:
      context: ../work_dir/zbc-oracle-db
      dockerfile: ./Dockerfile.local.dev
    ports:
      - "8001:8001"
    networks:
      localnet:
        ipv4_address: 192.167.10.12

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.10.0/16
