name: Publish Evmos node

on:
  workflow_dispatch:
    inputs:
      refToBuildEvmos:
        description: 'Branch, tag or commit SHA1 to checkout Evmos'
        required: true
        default: "feature/CI"
        type: string
      refToBuildGoEthereum:
        description: 'Branch, tag or commit SHA1 to checkout go-ethereum'
        required: true
        default: "petar/extensive-log"
        type: string
      refToBuildEthermint:
        description: 'Branch, tag or commit SHA1 to checkout Ethermint'
        required: true
        default: "v0.19.3-zama"
        type: string
      evmos_node_tag:
        description: 'Evmos node tag (default: latest)'
        default: "latest"
        type: string
        required: false

env:
  DOCKER_IMAGE: ghcr.io/zama-ai/evmos-node

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: evmos
          ref: ${{ inputs.refToBuildEvmos }}

      - name: PrepareGoEthereum
        uses: actions/checkout@v3
        with:
          repository: zama-ai/go-ethereum
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
          path: go-ethereum
          ref: ${{ inputs.refToBuildGoEthereum }}

      - name: PrepareEthermint
        uses: actions/checkout@v3
        with:
          repository: zama-ai/ethermint
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
          path: ethermint
          ref: ${{ inputs.refToBuildEthermint }}

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: evmos/docker/Dockerfile.evmos-node.testnet
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ inputs.evmos_node_tag }}
          labels: evmos_node

