name: Publish tfhe-rs C api

on: workflow_dispatch

env:
  DOCKER_IMAGE: ghcr.io/zama-ai/tfhe-rs-c-api

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile.tfhe-rs.testnet
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          labels: tfhe-rs-c-api
