name: Run e2e test

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: evmos
          ref: feature/CI
      
      - name: Checkout zbc-dev
        uses: actions/checkout@v3
        with:
          repository: zama-ai/zbc-development
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
          path: zbc-development
          ref: testnet-from-CI-images

      - name: Checkout zbc-solidity
        uses: actions/checkout@v3
        with:
          repository: zama-ai/zbc-solidity
          token: ${{ secrets.CONCRETE_ACTIONS_TOKEN }}
          path: zbc-solidity
          ref: feature/CI-testing

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Download keys from S3
        working-directory: ./zbc-development
        env:
          AWS_S3_BUCKET: zbc-testnet
        run: |
          aws s3 ls s3://${AWS_S3_BUCKET}/users-fhe-keys/
          ./prepare_volumes_ci.sh

      - name: Prepare files for node setup
        working-directory: ./zbc-development
        run: |
          mkdir -p node/evmos
          cp ../evmos/private.ed25519 node/evmos 
          cp ../evmos/public.ed25519 node/evmos 
          touch vm.log
          ls node/evmos

      - name: List files in volumes
        working-directory: ./zbc-development
        run: |
          ls volumes

      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Prepare evmos node aka run setup.sh
        working-directory: ./zbc-development
        run: |
          docker compose -f docker-compose.testnet.yml run validator bash /config/setup.sh
      

      - name: Check running node owner and change it 
        working-directory: ./zbc-development
        run: |
          ls -all .
          sudo chown -R runner:docker running_node/

      - name: Prepare test (called demo)
        working-directory: ./zbc-development
        run: |
          ./prepare_demo_testnet_ci.sh
      
      - name: Start whole testnet
        working-directory: ./zbc-development
        run: |
          docker compose  -f docker-compose.testnet.yml -f docker-compose.testnet.override.yml  up --detach

      - name: Set dummy mode
        working-directory: ./zbc-development
        run: |
          docker compose -f docker-compose.testnet.yml exec validator curl http://zkpok:23042/configure/mode/dummy
          
      - name: Run e2e test from zbc-solidty
        working-directory: ./zbc-solidty
        run: |
          ./run_ci_test.sh

      - name: Stop whole testnet
        working-directory: ./zbc-development
        run: |
          docker compose -f docker-compose.testnet.yml -f docker-compose.testnet.override.yml down
